// Auto-generated by LocalisationTermGenerator.cs on 2026-04-19 23:47:56 (E. Australia Standard Time)
// Do not modify; changes will be overwritten

namespace FishFlingers.Localisation
{
	public enum LocalisationTerm
	{
		// Browse Games Panel
		BrowseGamesPanelTitle = 566923365,

		// Building Kit Panel
		BuildingKitPanelTitle = 1649053697,
		BuildingKitPanelBuild = 1582183131,

		// Characters
		CharactersRaftPlayerName = 814387201,
		CharactersRaftPlayerDescription = 1347063821,
		CharactersFlyingFishName = 1439338514,
		CharactersFlyingFishDescription = 936022047,

		// Clam Chest Panel
		ClamChestPanelTitle = 1411739775,

		// Common
		CommonQuit = 1749717008,
		CommonLan = -1430432905,
		CommonSteam = -1417849993,

		// Entities
		EntitiesGoopTileName = -1642263902,
		EntitiesGoopTileDescription = -1596126558,
		EntitiesWoodenTileName = -1596126557,
		EntitiesWoodenTileDescription = -1596126560,
		EntitiesMetalTileName = -1596126559,
		EntitiesMetalTileDescription = -1596126554,
		EntitiesDroppedItemName = -1941270485,
		EntitiesDroppedItemDescription = -1999990735,

		// Fishing Bag Panel
		FishingBagPanelTitle = -1857384445,

		// Host Game Panel
		HostGamePanelTitle = -1880788874,

		// Main Menu Screen
		MainMenuScreenGameTitle = 1984598997,
		MainMenuScreenBrowseGames = -804614128,
		MainMenuScreenHostGame = 1510641791,

		// Structures
		StructuresWaveSignName = -490041344,
		StructuresWaveSignDescription = -708145142,
		StructuresClamChestName = -423162057,
		StructuresClamChestDescription = -402190537,

		// World Panel
		WorldPanelTitle = -1599770401,
		WorldPanelName = -1591381793,
		WorldPanelDefaultName = -1591381796,
		WorldPanelHost = 845510180,
	}
}
