// Auto-generated by LocalisationTermGenerator.cs on 2026-08-13 18:39:28 (E. Australia Standard Time)
// Do not modify; changes will be overwritten

namespace NoMoreFishAndChips.Localisation
{
	public enum LocalisationTerm
	{
		// Browse Games Panel
		BrowseGamesPanelTitle = 566923365,

		// Building Kit Panel
		BuildingKitPanelTitle = 1649053697,
		BuildingKitPanelBuild = 1582183131,

		// Characters
		CharactersRaftPlayerName = 814387201,
		CharactersRaftPlayerDescription = 1347063821,
		CharactersFlyingFishName = 1439338514,
		CharactersFlyingFishDescription = 936022047,

		// Clam Chest Panel
		ClamChestPanelTitle = 1411739775,
		ClamChestPanelChest = 1883767265,

		// Common
		CommonQuit = 1749717008,
		CommonLan = -1430432905,
		CommonSteam = -1417849993,

		// Crafting Kit Panel
		CraftingKitPanelTitle = 1579512034,
		CraftingKitPanelCraft = 1613066466,

		// Entities
		EntitiesGoopTileName = -1642263902,
		EntitiesGoopTileDescription = -1596126558,
		EntitiesWoodenTileName = -1596126557,
		EntitiesWoodenTileDescription = -1596126560,
		EntitiesMetalTileName = -1596126559,
		EntitiesMetalTileDescription = -1596126554,
		EntitiesDroppedItemName = -1941270485,
		EntitiesDroppedItemDescription = -1999990735,

		// Fishing Bag Panel
		FishingBagPanelTitle = -1857384445,

		// Giant Clams Mouth Panel
		GiantClamsMouthPanelTitle = 585486449,
		GiantClamsMouthPanelClam = -1754933598,

		// Host Game Panel
		HostGamePanelTitle = -1880788874,

		// Items
		ItemsDriftwoodName = -1880788664,
		ItemsDriftwoodDescription = -1843039928,
		ItemsGoopName = -1843039927,
		ItemsGoopDescription = -1843039926,
		ItemsHammerName = -1838845624,
		ItemsHammerDescription = -1838845623,
		ItemsPaddleName = -1838845622,
		ItemsPaddleDescription = -1838845621,
		ItemsScrapName = -1838845620,
		ItemsScrapDescription = -1838845619,
		ItemsPalmSeedName = 1122912567,
		ItemsPalmSeedDescription = 1152272695,
		ItemsSharkFinName = 1669874186,
		ItemsSharkFinDescription = 1703428618,
		ItemsFinBackName = 671836591,
		ItemsFinBackDescription = 671836590,
		ItemsToothSpearName = 470489249,
		ItemsToothSpearDescription = 474683553,
		ItemsMakoToothName = -2054487933,
		ItemsMakoToothDescription = -2054487934,
		ItemsShellFragmentName = -1754529274,
		ItemsShellFragmentDescription = -1733557754,

		// Main Menu Screen
		MainMenuScreenGameTitle = 1984598997,
		MainMenuScreenBrowseGames = -804614128,
		MainMenuScreenHostGame = 1510641791,

		// Settings Panel
		SettingsPanelTitle = -1293586224,

		// Stages
		StagesClamClusterName = -777686779,
		StagesSharkDenName = -744132347,
		StagesSquidStrongholdName = -744132348,

		// Structures
		StructuresWaveCounterName = 1671077837,
		StructuresWaveCounterDescription = 1696243661,
		StructuresClamChestName = -423162057,
		StructuresClamChestDescription = -402190537,
		StructuresPlanterName = -897745646,
		StructuresPlanterDescription = -868385518,

		// Voyage Board Panel
		VoyageBoardPanelTitle = 1164275977,
		VoyageBoardPanelSelectedSea = 1176858889,
		VoyageBoardPanelDifficulty = 1176858888,

		// Voyage Results Screen
		VoyageResultsScreenVictory = 744845695,
		VoyageResultsScreenDefeat = 786788735,
		VoyageResultsScreenReturnToLobby = 790983039,

		// Voyages
		VoyagesTemperateSeaName = 31814254,
		VoyagesTemperateSeaDescription = 48591470,

		// Widgets
		WidgetsInventoryTitle = -1511690128,
		WidgetsEquipmentTitle = -1494912912,
		WidgetsHotbarTitle = -1494912911,

		// World Panel
		WorldPanelTitle = -1599770401,
		WorldPanelName = -1591381793,
		WorldPanelDefaultName = -1591381796,
		WorldPanelHost = 845510180,
	}
}
