#if UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using ShinyOwl.Common;
using UnityEditor.Localization;
using System.Collections.Generic;
using UnityEngine.Localization.Tables;
using System.Text;
using System.Text.RegularExpressions;
using System.IO;
using ShinyOwl.Common.Utils;
using System;

namespace FishFlingers.Localisation
{
    public class LocalisationTermGenerator
    {
        private const string ScriptName = "LocalisationTerm";
        private const string ScriptPath = "Assets/Features/Localisation/" + ScriptName + ".cs";
        private const string TableSuffix = "Table";

        [MenuItem("Tools/Regenerate LocalisationTerm.cs")]
        public static void Regenerate()
        {
            StringBuilder builder = new();

            TimeZoneInfo timeZoneInfo = TimeZoneInfo.Local;
            string timeZoneName = timeZoneInfo.IsDaylightSavingTime(DateTime.Now) ? timeZoneInfo.DaylightName : timeZoneInfo.StandardName;
            builder.AppendLine($"// Auto-generated by {nameof(LocalisationTermGenerator)}.cs on {DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")} ({timeZoneName})");
            builder.AppendLine($"// Do not modify; changes will be overwritten");
            builder.AppendLine();

            builder.AppendLine($"namespace {typeof(LocalisationManager).Namespace}");
            builder.AppendLine($"{{");

            builder.AppendLine($"\tpublic enum {ScriptName}");
            builder.AppendLine($"\t{{");

            string[] guids = AssetDatabase.FindAssets($"t:{nameof(StringTableCollection)}");

            for (int i = 0; i < guids.Length; i++)
            {
                StringTableCollection collection = AssetDatabase.LoadAssetAtPath<StringTableCollection>(AssetDatabase.GUIDToAssetPath(guids[i]));

                // BrowseGamesPanelTable -> BrowseGamesPanel -> Browse Games Panel
                string tableComment = collection.TableCollectionName;
                tableComment = Regex.Replace(tableComment, $"{TableSuffix}$", "");
                tableComment = Regex.Replace(tableComment, "(?<!^)([A-Z])", " $1");
                builder.AppendLine($"\t\t// {tableComment}");

                foreach (SharedTableData.SharedTableEntry entry in collection.SharedData.Entries)
                {
                    // browseGamesPanel.title -> BrowseGamesPanelTitle
                    string key = Regex.Replace(entry.Key, @"(?:^|\.)(.)", match => match.Groups[1].Value.ToUpper());
                    int id = Utils.Math.HashLongToInt(entry.Id);
                    builder.AppendLine($"\t\t{key} = {id},");
                }

                if (i < guids.Length - 1)
                {
                    builder.AppendLine();
                }
            }

            builder.AppendLine($"\t}}");
            builder.AppendLine($"}}");

            File.WriteAllText(ScriptPath, builder.ToString());
        }
    }
}
#endif